"""Operator-only native Mac compatibility gate; no NBN/Typefully connection.

Run setup, sandbox, metadata, login, turn, resume in that order. Setup generates
only this pilot's runtime state; it never copies the desktop account or config.
"""
import argparse
import hashlib
import json
import os
from pathlib import Path
import subprocess
import sys
import time
import importlib.metadata

STATE = Path('/Users/brady/codex/nbn-reporter-pilot')
WORK = STATE / 'workspace'
CONTROL = STATE / 'control'
AUTH = STATE / 'codex'
RUNTIME = STATE / 'runtime'
CODEX = RUNTIME / 'cli/node_modules/@openai/codex-darwin-arm64/vendor/aarch64-apple-darwin/bin/codex'
PYTHON = RUNTIME / 'venv/bin/python'
CONFIG = AUTH / 'config.toml'
RECEIPT = CONTROL / 'sandbox-passed.json'


def runtime_env():
    return {'PATH': f'{RUNTIME}/cli/node_modules/.bin:/opt/homebrew/bin:/usr/bin:/bin',
            'CODEX_HOME': str(AUTH), 'LANG': 'en_US.UTF-8',
            'PLAYWRIGHT_BROWSERS_PATH': str(RUNTIME / 'browsers'),
            'PYTHONDONTWRITEBYTECODE': '1', 'TMPDIR': str(WORK / 'tmp')}


def setup():
    for folder in (STATE, WORK, WORK / 'tmp', CONTROL, AUTH, RUNTIME,
                   WORK / '.codex', WORK / '.agents'):
        folder.mkdir(parents=True, exist_ok=True)
    # Files generated by this bootstrap are not credentials. Never rewrite auth.json.
    permissions = {
        ':root': 'deny', ':minimal': 'read',
        '/System': 'read', '/usr': 'read', '/bin': 'read', '/sbin': 'read',
        '/opt/homebrew': 'read', str(RUNTIME): 'read',
        str(AUTH): 'deny', str(CONTROL): 'deny', str(WORK): 'write',
        str(WORK / '.codex'): 'read', str(WORK / '.agents'): 'read',
        str(WORK / 'AGENTS.md'): 'read',
    }
    content = '''model = "gpt-6-astra"
model_reasoning_effort = "medium"
service_tier = "default"
forced_login_method = "chatgpt"
cli_auth_credentials_store = "file"
approval_policy = "never"
web_search = "live"
default_permissions = "reporter"

[features]
apps = false
multi_agent = false
remote_plugin = false
tool_suggest = false

[permissions.reporter]
extends = ":workspace"

[permissions.reporter.filesystem]
'''
    content += '\n'.join(f'{json.dumps(k)} = {json.dumps(v)}' for k, v in permissions.items())
    content += '\n\n[permissions.reporter.network]\nenabled = false\n'
    content += f'\n[projects.{json.dumps(str(WORK))}]\ntrust_level = "trusted"\n'
    CONFIG.write_text(content)
    CONFIG.chmod(0o600)
    (WORK / 'AGENTS.md').write_text('# Isolated NBN reporter compatibility workspace\n'
                                  'Only the explicit operator test is authorized here.\n')
    (WORK / '.codex/config.toml').write_text('# Protected, intentionally empty.\n')
    for folder in (AUTH, CONTROL):
        (folder / 'probe-canary.txt').write_text('Public dummy sandbox canary; not a credential.\n')
    probe = Path(__file__).with_name('local_sandbox_canary.py')
    (RUNTIME / 'sandbox_canary.py').write_bytes(probe.read_bytes())
    print(json.dumps({'setup': str(STATE), 'auth_copied': False}))


def binding():
    canary = RUNTIME / 'sandbox_canary.py'
    if canary.read_bytes() != Path(__file__).with_name('local_sandbox_canary.py').read_bytes():
        raise SystemExit('Runtime canary differs from the reviewed source; run setup again.')
    files = (CONFIG, WORK / 'AGENTS.md', WORK / '.codex/config.toml', canary,
             CODEX, CODEX.with_name('codex-code-mode-host'),
             RUNTIME / 'cli/package-lock.json', Path(__file__))
    files += tuple(p for p in (RUNTIME / 'reporter_mcp.py',) if p.exists())
    return {'cwd': str(WORK.resolve()), 'codex_home': str(AUTH.resolve()),
            'profile': 'reporter', 'python': str(PYTHON.resolve()),
            'sdk': importlib.metadata.version('openai-codex'),
            'runtime': subprocess.check_output([str(CODEX), '--version'],
                                              env=runtime_env(), text=True).strip(),
            'hashes': {str(p): hashlib.sha256(p.read_bytes()).hexdigest() for p in files}}


def require_pass():
    if not RECEIPT.exists() or json.loads(RECEIPT.read_text()).get('binding') != binding():
        raise SystemExit('Fresh matching sandbox pass required before login or model use.')


def sandbox():
    RECEIPT.unlink(missing_ok=True)  # Invalidate only this generated test receipt.
    before = binding()
    result = subprocess.run([str(CODEX), 'sandbox', '-P', 'reporter', '--', str(PYTHON),
                             str(RUNTIME / 'sandbox_canary.py')],
                            cwd=WORK, env=runtime_env(), text=True,
                            capture_output=True, timeout=30)
    print(json.dumps({'exit_code': result.returncode, 'stdout': result.stdout,
                      'stderr': result.stderr[-4000:]}), flush=True)
    if result.returncode:
        raise SystemExit(result.returncode)
    payload = json.loads(result.stdout.strip().splitlines()[-1])
    if not payload.get('ok') or before != binding():
        raise SystemExit('Sandbox failed or runtime changed during probe.')
    RECEIPT.write_text(json.dumps({'at': time.time(), 'binding': before, 'checks': payload}))


def client():
    from openai_codex import Codex, CodexConfig
    return Codex(CodexConfig(codex_bin=str(CODEX), cwd=str(WORK), env=runtime_env(),
                            client_name='nbn_local_pilot', client_title='NBN Local Pilot'))


def wire_request(codex, method, params):
    # Stable SDK 147 omits CLI 154's activePermissionProfile from its typed response.
    # Preserve the actual wire fields with the public low-level request interface.
    from pydantic import BaseModel, ConfigDict
    class WireObject(BaseModel):
        model_config = ConfigDict(extra='allow')
    return codex._client.request(method, params, response_model=WireObject).model_dump()


def check_config(codex, *, reporter=False):
    effective = wire_request(codex, 'config/read', {'cwd': str(WORK), 'includeLayers': True})
    conf = effective['config']
    expected = {'model': 'gpt-6-astra', 'model_reasoning_effort': 'medium',
                'service_tier': 'default', 'approval_policy': 'never',
                'default_permissions': 'reporter', 'forced_login_method': 'chatgpt'}
    if any(conf.get(k) != v for k, v in expected.items()):
        raise RuntimeError('Unexpected reporter model, effort, billing, approval or permission setting.')
    if any(conf.get(k) for k in ('plugins', 'apps', 'browser_use',
                                'computer_use', 'desktop', 'hooks')):
        raise RuntimeError('Unexpected external tools or hooks in compatibility runtime.')
    servers = conf.get('mcp_servers') or {}
    if reporter:
        if set(servers) != {'nbn'}:
            raise RuntimeError('Only the NBN MCP server is allowed.')
        server = servers['nbn']
        if server.get('command') != str(PYTHON) or server.get('args') != [str(RUNTIME / 'reporter_mcp.py')]:
            raise RuntimeError('Unexpected reporter MCP command.')
        if server.get('required') is not True or server.get('env') or server.get('env_vars'):
            raise RuntimeError('MCP must be required with no forwarded credentials.')
    elif servers:
        raise RuntimeError('Compatibility check expected no MCP servers.')
    if any(conf.get('features', {}).get(k) is not False for k in
           ('apps', 'multi_agent', 'remote_plugin', 'tool_suggest')):
        raise RuntimeError('Unexpected application/plugin/agent tool surface.')
    if conf['permissions']['reporter']['network']['enabled'] is not False:
        raise RuntimeError('Shell network policy changed.')
    for layer in effective.get('layers', []):
        name = layer.get('name', {})
        if name.get('type') == 'project' and name.get('dotCodexFolder') != str(WORK / '.codex'):
            raise RuntimeError('Unexpected project configuration layer.')
        if name.get('type') == 'user' and name.get('file') != str(CONFIG):
            raise RuntimeError('Unexpected account configuration layer.')
    CONTROL.joinpath('effective-config.json').write_text(json.dumps(effective, indent=2))
    return effective


def metadata():
    import openai_codex
    with client() as codex:
        effective = check_config(codex)
        print(json.dumps({'sdk': openai_codex.__version__, 'runtime': binding()['runtime'],
                          'account_present': codex.account().account is not None,
                          'astra_available': any(m.model == 'gpt-6-astra' for m in codex.models().data),
                          'publishing': 'unavailable'}), flush=True)
        print(json.dumps({'config_check': 'passed',
                          'layers': [l.get('name') for l in effective.get('layers', [])]}), flush=True)


def login():
    require_pass()
    with client() as codex:
        handle = codex.login_chatgpt_device_code()
        print(json.dumps({'verification_url': handle.verification_url,
                          'user_code': handle.user_code}), flush=True)
        print(json.dumps({'login_success': handle.wait().success}), flush=True)


def checked_thread(codex, resume=False):
    from openai_codex import Thread
    check_config(codex)
    record = CONTROL / 'probe-session.json'
    params = {'model': 'gpt-6-astra', 'cwd': str(WORK), 'approvalPolicy': 'never',
              'serviceTier': 'default', 'developerInstructions':
                  'Bounded runtime compatibility check. No publishing, research or system changes. '
                  'Follow only the explicit test.'}
    if resume:
        params['threadId'] = json.loads(record.read_text())['thread_id']
    actual = wire_request(codex, 'thread/resume' if resume else 'thread/start', params)
    audit = {k: actual.get(k) for k in ('cwd', 'instructionSources', 'model', 'modelProvider',
             'reasoningEffort', 'serviceTier', 'approvalPolicy', 'activePermissionProfile', 'sandbox')}
    CONTROL.joinpath('session-audit.json').write_text(json.dumps(audit, indent=2))
    print(json.dumps({'resolved_session': audit}), flush=True)
    expected = {'cwd': str(WORK), 'model': 'gpt-6-astra', 'modelProvider': 'openai',
                'reasoningEffort': 'medium', 'serviceTier': 'default', 'approvalPolicy': 'never'}
    if any(audit.get(k) != v for k, v in expected.items()):
        raise RuntimeError('Session settings differ from approved pilot settings.')
    if (audit.get('activePermissionProfile') or {}).get('id') != 'reporter':
        raise RuntimeError('Reporter permission profile is not active.')
    if audit.get('instructionSources') != [str(WORK / 'AGENTS.md')]:
        raise RuntimeError('Unexpected instruction source loaded.')
    if resume and actual['thread']['id'] != params['threadId']:
        raise RuntimeError('Exact-session continuity failed.')
    record.write_text(json.dumps({'thread_id': actual['thread']['id']}))
    return Thread(codex._client, actual['thread']['id'])


def session():
    require_pass()
    with client() as codex:
        checked_thread(codex)


def turn(resume=False):
    require_pass()
    with client() as codex:
        thread = checked_thread(codex, resume)
        if resume:
            prompt = 'What was the continuity phrase? Reply with that phrase only. No tools needed.'
        else:
            prompt = ('Remember the phrase cedar lighthouse. Run pwd once to verify the sandboxed '
                      'shell and reply READY. Do not inspect files or search the internet.')
        result = thread.run(prompt, effort='medium', service_tier='default')
        print(json.dumps({'thread_id': thread.id, 'status': str(result.status),
                          'response': result.final_response,
                          'usage': result.usage.model_dump(mode='json') if result.usage else None}), flush=True)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('action', choices=['setup', 'sandbox', 'metadata', 'login', 'session', 'turn', 'resume'])
    action = parser.parse_args().action
    if action != 'setup':
        # SDK merges config.env into os.environ; sanitize the child process itself.
        os.environ.clear()
        os.environ.update(runtime_env())
        os.chdir(WORK)
    turn(resume=True) if action == 'resume' else globals()[action]()
